# Generated by Django 3.2.13 on 2022-06-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number_of_people', models.IntegerField()),
                ('time_and_date', models.DateTimeField()),
            ],
        ),
    ]
